server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    hikari:
      auto-commit: false
    password: ***REMOVED***
    url: jdbc:postgresql://172.17.0.1:5432/speedreadingapp
    username: speedreadingapp
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
